---
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone master
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Validate Dockerfile
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Dockerfile

      - name: Sysdig CIS Dockerfile Benchmark
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          path: .
          fail-build: true
          severity-cutoff: critical

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/${{ github.repository }}:latest
        args: --file=Dockerfile

    - name: Upload scan result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
      sarif_file: snyk.sarif
