---
name: Workstation Terraform

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: workstation

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 0.12.25
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Terraform Format'
        run: terraform fmt --check
        continue-on-error: true

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate -no-color
        continue-on-error: true

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan  -no-color
...
